### ISSUE TITLE
how to use rxjs in angular?

### ISSUE THREAD

**Issue by joelgenaro** [joelgenaro/Angular-Live-coding-Test#1]
i have a angular project and how to use rxjs?

**Comment by malachijonesuy** [comment]
here is my solution.

import { Component, OnInit } from '@angular/core';
import { Observable, interval } from 'rxjs';
import { map, filter } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  template: `
    <h1>Observable Example</h1>
    <p>{{ message }}</p>
  `
})
export class AppComponent implements OnInit {
  message: string;

  ngOnInit() {
    const numbers$: Observable<number> = interval(1000); // Emit a number every second

    numbers$
      .pipe(
        filter(num => num % 2 === 0), // Filter only even numbers
        map(num => `Number: ${num}`) // Transform the emitted numbers
      )
      .subscribe(
        transformedNum => {
          this.message = transformedNum; // Update the message with the transformed number
        }
      );
  }
}

import { Component, OnInit, OnDestroy } from '@angular/core';
import { Observable, interval, Subscription } from 'rxjs';
import { map, filter } from 'rxjs/operators';

@Component({
  // Component configuration...
})
export class AppComponent implements OnInit, OnDestroy {
  message: string;
  subscription: Subscription;

  ngOnInit() {
    const numbers$: Observable<number> = interval(1000);

    this.subscription = numbers$
      .pipe(
        filter(num => num % 2 === 0),
        map(num => `Number: ${num}`)
      )
      .subscribe(transformedNum => {
        this.message = transformedNum;
      });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
